# Graphics
TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true
HAVE_SYNAPTICS_I2C_RMI4_FW_UPGRADE := true
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 5000000
VSYNC_EVENT_PHASE_OFFSET_NS := 7500000
TARGET_ENABLE_QC_AV_ENHANCEMENTS := true
BOARD_USES_HWCOMPOSER := true
BOARD_GLOBAL_CFLAGS += -DBATTERY_REAL_INFO
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true
