# TWRP RECOVERY SPECIFIC FLAG
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_THEME := portrait_hdpi
TW_DEFAULT_BRIGHTNESS := 120
TW_EXCLUDE_SUPERSU := true
TW_NEW_ION_HEAP := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_NO_USB_STORAGE := true
TWRP_INCLUDE_LOGCAT := true

# Asian region languages
TW_EXTRA_LANGUAGES := true
